In [ ]:
!pip3 install torch

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import torch
import numpy as np

In [ ]:
v = torch.tensor([1, 2, 3])
print(v)
print(v.dtype)
print(v[0])
print(v[1])
print(v[2])

tensor([1, 2, 3])
torch.int64
tensor(1)
tensor(2)
tensor(3)


In [ ]:
v = torch.tensor([1, 2, 3, 4, 5, 6])
print(v[1:4])
print(v[1:])

tensor([2, 3, 4])
tensor([2, 3, 4, 5, 6])


In [ ]:
f = torch.FloatTensor([1, 2, 3, 4, 5, 6])
print(f)
print(f.dtype)
print(f.size)

tensor([1., 2., 3., 4., 5., 6.])
torch.float32
<built-in method size of Tensor object at 0x7f457da24dd0>


In [ ]:
v.view(6, 1) # reshpage the tensor. similar to numpy reshape

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [ ]:
v.view(3, 2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
v.view(3, -1) # 마지막에 -1을 해주면 마지막 행렬의 수를 자동으로 계산해 준다

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
a = np.array([1, 2, 3, 4, 5])
tensor_cnv = torch.from_numpy(a)
print(tensor_cnv)
print(tensor_cnv.type())

tensor([1, 2, 3, 4, 5])
torch.LongTensor


In [ ]:
numpy_cnv = tensor_cnv.numpy()
print(numpy_cnv)

[1 2 3 4 5]
