In [1]:
!pip install torch

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import torch

In [4]:
one_d = torch.arange(2, 7)
one_d

tensor([2, 3, 4, 5, 6])

In [5]:
one_d = torch.arange(2, 7, 2)
one_d

tensor([2, 4, 6])

In [6]:
one_d = torch.arange(0, 9)
one_d

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
two_d = one_d.view(3, 3)
two_d

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [9]:
two_d.dim()

2

In [10]:
two_d[0]

tensor([0, 1, 2])

In [11]:
two_d[0, 0]

tensor(0)

In [12]:
two_d[1, 2]

tensor(5)

In [14]:
x = torch.arange(18).view(2, 3, 3) # 2 dimentional, 3rows, 3columns
x

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]])

In [15]:
x = torch.arange(18).view(3, 3, 2)
x

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]]])

In [16]:
x[1, 1, 1]

tensor(9)

In [17]:
x = torch.arange(18).view(3, 2, 3)
x

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]])

In [18]:
x[1, 1, 1]

tensor(10)

In [19]:
x[1, 0:2, 1]

tensor([ 7, 10])

In [20]:
x[1, 0:2, 0:3]

tensor([[ 6,  7,  8],
        [ 9, 10, 11]])

In [21]:
x[1, :, 0:3]

tensor([[ 6,  7,  8],
        [ 9, 10, 11]])

In [22]:
x[1, :, :]

tensor([[ 6,  7,  8],
        [ 9, 10, 11]])